### ISSUE TITLE
iscsiadm prerequisite

### ISSUE THREAD

**Issue by toralux** [zebernst/synology-csi-talos#11]
The helm chart mention a iscsiadm installed on every cluster node prerequisite.
How is this accomplished? Will installing the iscsi-tools Talos extension (https://github.com/siderolabs/extensions/tree/main/storage/iscsi-tools) fulfil this prerequisite?

**Comment by zebernst** [comment]
You can see my declarative node setup here if you're curious: https://github.com/zebernst/homelab/blob/main/kubernetes/bootstrap/talos/talconfig.yaml

There's nothing I had to do beyond what's in that file to get the driver working.

**Comment by toralux** [comment]
Thanks for clarification, and thanks for your effort adding Talos support!

**Comment by toralux** [comment]
From https://github.com/zebernst/homelab/blob/main/kubernetes/bootstrap/talos/talconfig.yaml it looks like iscsi-tools extension is only needed for the worker nodes. I guess the helm chart guide saying `iscsiadm installed on every cluster node.` could also be more accurate telling iscsi-tools extension is only needed for worker nodes, and not control plane nodes in the cluster (if this is correct).
